#config_version=5

displays:
  window:
    width: 800
    height: 600
  dmd:
    width: 160
    height: 120
    default: true
    round_anchor_x: left
    round_anchor_y: bottom

slides:
  window_slide:
    - type: display
      effects:
        - type: color_dmd
          # dot_size: .5
          # dot_filter: true
          # blur: 0
      width: 800
      height: 600
  dmd_slide:
    - type: text
      text: DOTS!
      style: header_md

slide_player:
  init_done:
    window_slide:
      target: window
    dmd_slide:
      target: dmd

widget_styles:
  header_md:
    font_size: 10
    font_name: Quadrit-10
    line_height: 0.75
    adjust_bottom: 6
    adjust_top: 1
    z: 1
